// <auto-generated />
using System;
using GameSaleProject_DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameSaleProject_DataAccess.Migrations
{
    [DbContext(typeof(GameSaleProjectDbContext))]
    [Migration("20240830173559_newseeddata")]
    partial class newseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(697),
                            Description = "Action games",
                            IsDeleted = false,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(708),
                            Description = "Adventure games",
                            IsDeleted = false,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(709),
                            Description = "Role-playing games",
                            IsDeleted = false,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(710),
                            Description = "Strategy games",
                            IsDeleted = false,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(712),
                            Description = "Simulation games",
                            IsDeleted = false,
                            Name = "Simulation"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(713),
                            Description = "High-speed racing games",
                            IsDeleted = false,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(714),
                            Description = "Survival games with challenging gameplay",
                            IsDeleted = false,
                            Name = "Survival"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(714),
                            Description = "Puzzle-solving games with various challenges",
                            IsDeleted = false,
                            Name = "Puzzle"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(715),
                            Description = "Games set in dark, mysterious worlds",
                            IsDeleted = false,
                            Name = "Dark Fantasy"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(776),
                            Description = "Sci-fi games with space exploration",
                            IsDeleted = false,
                            Name = "Sci-Fi"
                        });
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("GameName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An open-world RPG game",
                            Developer = "CD Projekt Red",
                            Discount = 0,
                            GameName = "The Witcher 3: Wild Hunt",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 39.99m,
                            PublisherId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An action-adventure game",
                            Developer = "Rockstar North",
                            Discount = 20,
                            GameName = "Grand Theft Auto V",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 29.99m,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A futuristic RPG game",
                            Developer = "CD Projekt Red",
                            Discount = 10,
                            GameName = "Cyberpunk 2077",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 59.99m,
                            PublisherId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An open-world adventure game",
                            Developer = "Rockstar Studios",
                            Discount = 0,
                            GameName = "Red Dead Redemption 2",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 49.99m,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A strategy game",
                            Developer = "Firaxis Games",
                            Discount = 0,
                            GameName = "Civilization VI",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 39.99m,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2014, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A life simulation game",
                            Developer = "Maxis",
                            Discount = 0,
                            GameName = "The Sims 4",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 49.99m,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2016, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An action RPG game",
                            Developer = "FromSoftware",
                            Discount = 0,
                            GameName = "Dark Souls III",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 59.99m,
                            PublisherId = 5
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A sandbox game",
                            Developer = "Mojang",
                            Discount = 0,
                            GameName = "Minecraft",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 26.95m,
                            PublisherId = 6
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2017, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A battle royale game",
                            Developer = "Epic Games",
                            Discount = 0,
                            GameName = "Fortnite",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 0m,
                            PublisherId = 7
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2016, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A farming simulation game",
                            Developer = "ConcernedApe",
                            Discount = 0,
                            GameName = "Stardew Valley",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 14.99m,
                            PublisherId = 8
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An epic journey through enchanted lands.",
                            Developer = "Enchanted Studios",
                            Discount = 15,
                            GameName = "Mystic Quest",
                            IsDeleted = false,
                            Platform = "PC, PS5, Xbox",
                            Price = 29.99m,
                            PublisherId = 9
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Explore the far reaches of the galaxy.",
                            Developer = "Galaxy Games",
                            Discount = 20,
                            GameName = "Space Odyssey",
                            IsDeleted = false,
                            Platform = "PC, Xbox",
                            Price = 49.99m,
                            PublisherId = 12
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A fast-paced cyberpunk adventure.",
                            Developer = "Neon Visions",
                            Discount = 10,
                            GameName = "Cyber Runner",
                            IsDeleted = false,
                            Platform = "PC, PS5",
                            Price = 39.99m,
                            PublisherId = 13
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Uncover the secrets of lost civilizations.",
                            Developer = "Relic Games",
                            Discount = 25,
                            GameName = "Ancient Ruins",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 24.99m,
                            PublisherId = 14
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Build and manage your own fantasy empire.",
                            Developer = "Kingdom Creations",
                            Discount = 30,
                            GameName = "Fantasy Kingdom",
                            IsDeleted = false,
                            Platform = "PC, PS5",
                            Price = 19.99m,
                            PublisherId = 15
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2023, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hunt down ferocious dragons in an epic RPG.",
                            Developer = "Mythic Studios",
                            Discount = 20,
                            GameName = "Dragon Slayer",
                            IsDeleted = false,
                            Platform = "PC, Xbox, PS5",
                            Price = 59.99m,
                            PublisherId = 16
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-speed racing across various terrains.",
                            Developer = "Speedy Devs",
                            Discount = 15,
                            GameName = "Racing Thunder",
                            IsDeleted = false,
                            Platform = "PC, Xbox, Switch",
                            Price = 34.99m,
                            PublisherId = 17
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2023, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Survive the zombie apocalypse.",
                            Developer = "Apocalypse Now",
                            Discount = 25,
                            GameName = "Zombie Survival",
                            IsDeleted = false,
                            Platform = "PC, PS5, Xbox",
                            Price = 14.99m,
                            PublisherId = 18
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2023, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Solve challenging puzzles in this mind-bending game.",
                            Developer = "Mind Games",
                            Discount = 10,
                            GameName = "Puzzle Master",
                            IsDeleted = false,
                            Platform = "PC",
                            Price = 9.99m,
                            PublisherId = 19
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "An epic RPG where you become the hero.",
                            Developer = "Heroic Studios",
                            Discount = 15,
                            GameName = "Hero's Journey",
                            IsDeleted = false,
                            Platform = "PC, PS5, Xbox",
                            Price = 44.99m,
                            PublisherId = 10
                        });
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.GameSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDiscountApplied")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFullyRefunded")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GameSales");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.GameSaleDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("GameSaleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRefunded")
                        .HasColumnType("bit");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("GameSaleId");

                    b.ToTable("GameSaleDetails");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("ImageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1057),
                            GameId = 1,
                            ImageType = "card",
                            ImageUrl = "/images/witcher3.jpg",
                            IsDeleted = false,
                            Name = "witcher3"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1059),
                            GameId = 2,
                            ImageType = "card",
                            ImageUrl = "/images/gtav.jpg",
                            IsDeleted = false,
                            Name = "gtav"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1060),
                            GameId = 3,
                            ImageUrl = "/images/cyberpunk2077.jpg",
                            IsDeleted = false,
                            Name = "cyberpunk2077"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1061),
                            GameId = 4,
                            ImageType = "card",
                            ImageUrl = "/images/rdr2.jpg",
                            IsDeleted = false,
                            Name = "rdr2"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1062),
                            GameId = 5,
                            ImageType = "card",
                            ImageUrl = "/images/civ6.jpg",
                            IsDeleted = false,
                            Name = "civ6"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1063),
                            GameId = 6,
                            ImageType = "card",
                            ImageUrl = "/images/sims4.jpg",
                            IsDeleted = false,
                            Name = "sims4"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1064),
                            GameId = 7,
                            ImageType = "card",
                            ImageUrl = "/images/darksouls3.jpg",
                            IsDeleted = false,
                            Name = "darksouls3"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1065),
                            GameId = 8,
                            ImageType = "card",
                            ImageUrl = "/images/minecraft.jpg",
                            IsDeleted = false,
                            Name = "minecraft"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1066),
                            GameId = 9,
                            ImageType = "card",
                            ImageUrl = "/images/fortnite.jpg",
                            IsDeleted = false,
                            Name = "fortnite"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1067),
                            GameId = 10,
                            ImageType = "card",
                            ImageUrl = "/images/stardewvalley.jpg",
                            IsDeleted = false,
                            Name = "stardewvalley"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1067),
                            GameId = 7,
                            ImageType = "carousel",
                            ImageUrl = "/images/darksouls3Caus.jpg",
                            IsDeleted = false,
                            Name = "darksouls3Caus"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1068),
                            GameId = 4,
                            ImageType = "carousel",
                            ImageUrl = "/images/rdr2Caus.jpg",
                            IsDeleted = false,
                            Name = "rdr2Caus"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1069),
                            GameId = 9,
                            ImageType = "carousel",
                            ImageUrl = "/images/fortniteCaus.jpg",
                            IsDeleted = false,
                            Name = "fortniteCaus"
                        });
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1012),
                            IsDeleted = false,
                            Name = "CD Projekt"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1013),
                            IsDeleted = false,
                            Name = "Rockstar Games"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1014),
                            IsDeleted = false,
                            Name = "2K Games"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1015),
                            IsDeleted = false,
                            Name = "Electronic Arts"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1016),
                            IsDeleted = false,
                            Name = "Bandai Namco Entertainment"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1017),
                            IsDeleted = false,
                            Name = "Mojang"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1017),
                            IsDeleted = false,
                            Name = "Epic Games"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1018),
                            IsDeleted = false,
                            Name = "ConcernedApe"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1018),
                            IsDeleted = false,
                            Name = "Enchanted Publishing"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1019),
                            IsDeleted = false,
                            Name = "Heroic Media"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1020),
                            IsDeleted = false,
                            Name = "Dark Realm Publishing"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1020),
                            IsDeleted = false,
                            Name = "StarForge Media"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1021),
                            IsDeleted = false,
                            Name = "Silent Shadows Inc."
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1021),
                            IsDeleted = false,
                            Name = "Sandstorm Media"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1022),
                            IsDeleted = false,
                            Name = "Royal Publishing"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1023),
                            IsDeleted = false,
                            Name = "Black Flag Studios"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1023),
                            IsDeleted = false,
                            Name = "Crawl Publishers"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1024),
                            IsDeleted = false,
                            Name = "Urban Creations"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1025),
                            IsDeleted = false,
                            Name = "Wild Hunt Publishing"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1025),
                            IsDeleted = false,
                            Name = "NeoSpeed Studios"
                        });
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerReview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.SystemRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Graphics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemMemory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SystemProcessor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("SystemRequirements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1134),
                            GameId = 2,
                            Graphics = "NVIDIA GTX 660 2GB",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "72 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel Core i5-3470"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1137),
                            GameId = 3,
                            Graphics = "NVIDIA GTX 1060 6GB",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "70 GB",
                            SystemMemory = "12 GB",
                            SystemProcessor = "Intel Core i7-4790"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1139),
                            GameId = 4,
                            Graphics = "NVIDIA GTX 770 2GB",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "150 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel Core i5-2500K"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1140),
                            GameId = 5,
                            Graphics = "Intel HD Graphics 4000",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "12 GB",
                            SystemMemory = "4 GB",
                            SystemProcessor = "Intel Core i3-3225"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1141),
                            GameId = 6,
                            Graphics = "AMD Radeon HD 6870",
                            IsDeleted = false,
                            OS = "Windows 7",
                            Storage = "8 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel Core i5-2500"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1142),
                            GameId = 7,
                            Graphics = "Intel HD Graphics 4000",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "1 GB",
                            SystemMemory = "4 GB",
                            SystemProcessor = "Intel Core i3-3210"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1143),
                            GameId = 8,
                            Graphics = "Intel HD Graphics 620",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "20 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel Core i5-7300U"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1145),
                            GameId = 9,
                            Graphics = "Intel HD Graphics 3000",
                            IsDeleted = false,
                            OS = "Windows 7",
                            Storage = "500 MB",
                            SystemMemory = "2 GB",
                            SystemProcessor = "Intel Core i3-2100"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1146),
                            GameId = 10,
                            Graphics = "NVIDIA GTX 1080 8GB",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "100 GB",
                            SystemMemory = "16 GB",
                            SystemProcessor = "Intel Core i7-6700K"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1147),
                            GameId = 11,
                            Graphics = "NVIDIA GTX 1050 Ti",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "50 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel i5-9600K"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1148),
                            GameId = 12,
                            Graphics = "NVIDIA GTX 1660 Super",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "60 GB",
                            SystemMemory = "16 GB",
                            SystemProcessor = "AMD Ryzen 5 3600"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1149),
                            GameId = 13,
                            Graphics = "NVIDIA RTX 2060",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "40 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel i7-10700K"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1150),
                            GameId = 14,
                            Graphics = "NVIDIA GTX 1060",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "30 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "AMD Ryzen 3 3300X"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1151),
                            GameId = 15,
                            Graphics = "NVIDIA GTX 1050 Ti",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "25 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel i5-10400F"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1152),
                            GameId = 16,
                            Graphics = "NVIDIA RTX 2070 Super",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "80 GB",
                            SystemMemory = "16 GB",
                            SystemProcessor = "Intel i7-9700K"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1153),
                            GameId = 17,
                            Graphics = "NVIDIA GTX 1650",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "45 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "AMD Ryzen 5 2600"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1154),
                            GameId = 18,
                            Graphics = "NVIDIA GTX 1050",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "35 GB",
                            SystemMemory = "8 GB",
                            SystemProcessor = "Intel i5-9400F"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1155),
                            GameId = 19,
                            Graphics = "Intel UHD Graphics 630",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "20 GB",
                            SystemMemory = "4 GB",
                            SystemProcessor = "Intel i3-8100"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2024, 8, 30, 20, 35, 58, 539, DateTimeKind.Local).AddTicks(1156),
                            GameId = 20,
                            Graphics = "NVIDIA RTX 2060 Super",
                            IsDeleted = false,
                            OS = "Windows 10",
                            Storage = "50 GB",
                            SystemMemory = "16 GB",
                            SystemProcessor = "AMD Ryzen 5 3600X"
                        });
                });

            modelBuilder.Entity("GameSaleProject_Entity.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("GameSaleProject_Entity.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("/images/DefaultPfp.jpg");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Game", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Entities.Category", "Category")
                        .WithMany("Games")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameSaleProject_Entity.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.GameSale", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", "User")
                        .WithMany("GameSales")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.GameSaleDetail", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Entities.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameSaleProject_Entity.Entities.GameSale", "GameSale")
                        .WithMany("GameSaleDetails")
                        .HasForeignKey("GameSaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("GameSale");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Image", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Entities.Game", "Game")
                        .WithMany("Images")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Publisher", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Review", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Entities.Game", "Game")
                        .WithMany("Reviews")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.SystemRequirement", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Entities.Game", "Game")
                        .WithOne("SystemRequirement")
                        .HasForeignKey("GameSaleProject_Entity.Entities.SystemRequirement", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("GameSaleProject_Entity.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Category", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Game", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("SystemRequirement")
                        .IsRequired();
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.GameSale", b =>
                {
                    b.Navigation("GameSaleDetails");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Entities.Publisher", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GameSaleProject_Entity.Identity.AppUser", b =>
                {
                    b.Navigation("GameSales");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
